# ============================================================================
# Docker Compose Configuration for Staging Environment
# ============================================================================
# Usage: docker compose -f compose.staging.yaml up -d
# ============================================================================

services:
  portal-app:
    image: ghcr.io/${GITHUB_REPOSITORY:-allthingslinux/portal}:${IMAGE_TAG:-staging-latest}
    container_name: portal-app-staging
    restart: unless-stopped
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"  # Staging on port 3001, production will use 3000
    depends_on:
      portal-db-staging:
        condition: service_healthy
    networks:
      - portal-staging
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  portal-db-staging:
    image: postgres:18-alpine
    container_name: portal-db-staging
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-portal_staging}
    ports:
      - "5433:5432"  # Staging DB on port 5433, production will use 5432
    volumes:
      - portal-db-staging-data:/var/lib/postgresql/data
    networks:
      - portal-staging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  portal-db-staging-data:
    name: portal-db-staging-data

networks:
  portal-staging:
    name: portal-staging
    driver: bridge
