// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: ef7aad6d710fc0b45cb2be4900465c1e10f6d817c71a1b4c14e1fd3f9b11a70a


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "portal-theme";

export const themeNames: ThemeName[] = ["portal-theme"];

export type KcEnvName = "PORTAL_LOGO_URL" | "PORTAL_THEME_COLOR" | "PORTAL_SITE_URL";

export const kcEnvNames: KcEnvName[] = ["PORTAL_LOGO_URL", "PORTAL_THEME_COLOR", "PORTAL_SITE_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "PORTAL_LOGO_URL": "",
  "PORTAL_THEME_COLOR": "#000000",
  "PORTAL_SITE_URL": "http://localhost:3000"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
