-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."app_permissions" AS ENUM('roles.manage', 'settings.manage', 'members.manage', 'invites.manage');--> statement-breakpoint
CREATE TYPE "public"."notification_channel" AS ENUM('in_app', 'email');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('info', 'warning', 'error');--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"primary_owner_user_id" uuid DEFAULT auth.uid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" text,
	"email" varchar(320),
	"is_personal_account" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	"picture_url" varchar(1000),
	"public_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "accounts_slug_key" UNIQUE("slug"),
	CONSTRAINT "accounts_email_key" UNIQUE("email"),
	CONSTRAINT "accounts_slug_null_if_personal_account_true" CHECK (((is_personal_account = true) AND (slug IS NULL)) OR ((is_personal_account = false) AND (slug IS NOT NULL)))
);
--> statement-breakpoint
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "config" (
	"enable_team_accounts" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "invitations" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"account_id" uuid NOT NULL,
	"invited_by" uuid NOT NULL,
	"role" varchar(50) NOT NULL,
	"invite_token" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"expires_at" timestamp with time zone DEFAULT (CURRENT_TIMESTAMP + '7 days'::interval) NOT NULL,
	CONSTRAINT "invitations_email_account_id_key" UNIQUE("email","account_id"),
	CONSTRAINT "invitations_invite_token_key" UNIQUE("invite_token")
);
--> statement-breakpoint
ALTER TABLE "invitations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nonces" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_token" text NOT NULL,
	"nonce" text NOT NULL,
	"user_id" uuid,
	"purpose" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"used_at" timestamp with time zone,
	"revoked" boolean DEFAULT false NOT NULL,
	"revoked_reason" text,
	"verification_attempts" integer DEFAULT 0 NOT NULL,
	"last_verification_at" timestamp with time zone,
	"last_verification_ip" "inet",
	"last_verification_user_agent" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"scopes" text[] DEFAULT '{""}'
);
--> statement-breakpoint
ALTER TABLE "nonces" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_id" uuid NOT NULL,
	"type" "notification_type" DEFAULT 'info' NOT NULL,
	"body" varchar(5000) NOT NULL,
	"link" varchar(255),
	"channel" "notification_channel" DEFAULT 'in_app' NOT NULL,
	"dismissed" boolean DEFAULT false NOT NULL,
	"expires_at" timestamp with time zone DEFAULT (now() + '1 mon'::interval),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role" varchar(50) NOT NULL,
	"permission" "app_permissions" NOT NULL,
	CONSTRAINT "role_permissions_role_permission_key" UNIQUE("role","permission")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "roles" (
	"name" varchar(50) PRIMARY KEY NOT NULL,
	"hierarchy_level" integer NOT NULL,
	CONSTRAINT "roles_hierarchy_level_key" UNIQUE("hierarchy_level"),
	CONSTRAINT "roles_hierarchy_level_check" CHECK (hierarchy_level > 0)
);
--> statement-breakpoint
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "accounts_memberships" (
	"user_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"account_role" varchar(50) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	CONSTRAINT "accounts_memberships_pkey" PRIMARY KEY("user_id","account_id")
);
--> statement-breakpoint
ALTER TABLE "accounts_memberships" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_primary_owner_user_id_fkey" FOREIGN KEY ("primary_owner_user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."roles"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nonces" ADD CONSTRAINT "nonces_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."roles"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_memberships" ADD CONSTRAINT "accounts_memberships_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_memberships" ADD CONSTRAINT "accounts_memberships_account_role_fkey" FOREIGN KEY ("account_role") REFERENCES "public"."roles"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_memberships" ADD CONSTRAINT "accounts_memberships_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_memberships" ADD CONSTRAINT "accounts_memberships_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_memberships" ADD CONSTRAINT "accounts_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_accounts_is_personal_account" ON "accounts" USING btree ("is_personal_account" bool_ops);--> statement-breakpoint
CREATE INDEX "ix_accounts_primary_owner_user_id" ON "accounts" USING btree ("primary_owner_user_id" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_personal_account" ON "accounts" USING btree ("primary_owner_user_id" uuid_ops) WHERE (is_personal_account = true);--> statement-breakpoint
CREATE INDEX "ix_invitations_account_id" ON "invitations" USING btree ("account_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_nonces_status" ON "nonces" USING btree ("client_token" text_ops,"user_id" text_ops,"purpose" text_ops,"expires_at" text_ops) WHERE ((used_at IS NULL) AND (revoked = false));--> statement-breakpoint
CREATE INDEX "idx_nonces_verify_lookup" ON "nonces" USING btree ("purpose" text_ops,"expires_at" text_ops,"user_id" text_ops) WHERE ((used_at IS NULL) AND (revoked = false));--> statement-breakpoint
CREATE INDEX "idx_notifications_account_dismissed" ON "notifications" USING btree ("account_id" timestamptz_ops,"dismissed" timestamptz_ops,"expires_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_role_permissions_role" ON "role_permissions" USING btree ("role" text_ops);--> statement-breakpoint
CREATE INDEX "ix_accounts_memberships_account_id" ON "accounts_memberships" USING btree ("account_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "ix_accounts_memberships_account_role" ON "accounts_memberships" USING btree ("account_role" text_ops);--> statement-breakpoint
CREATE INDEX "ix_accounts_memberships_user_id" ON "accounts_memberships" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE VIEW "public"."user_account_workspace" AS (SELECT id, name, picture_url FROM accounts WHERE primary_owner_user_id = (( SELECT auth.uid() AS uid)) AND is_personal_account = true LIMIT 1);--> statement-breakpoint
CREATE VIEW "public"."user_accounts" AS (SELECT account.id, account.name, account.picture_url, account.slug, membership.account_role AS role FROM accounts account JOIN accounts_memberships membership ON account.id = membership.account_id WHERE membership.user_id = (( SELECT auth.uid() AS uid)) AND account.is_personal_account = false AND (account.id IN ( SELECT accounts_memberships.account_id FROM accounts_memberships WHERE accounts_memberships.user_id = (( SELECT auth.uid() AS uid)))));--> statement-breakpoint
CREATE POLICY "accounts_read" ON "accounts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((( SELECT auth.uid() AS uid) = primary_owner_user_id) OR has_role_on_account(id) OR is_account_team_member(id)));--> statement-breakpoint
CREATE POLICY "accounts_self_update" ON "accounts" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "create_org_account" ON "accounts" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "delete_team_account" ON "accounts" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "restrict_mfa_accounts" ON "accounts" AS RESTRICTIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "super_admins_access_accounts" ON "accounts" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "public config can be read by authenticated users" ON "config" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "super_admins_access_invitations" ON "invitations" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_super_admin());--> statement-breakpoint
CREATE POLICY "invitations_create_self" ON "invitations" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "invitations_delete" ON "invitations" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "invitations_read_self" ON "invitations" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "invitations_update" ON "invitations" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "restrict_mfa_invitations" ON "invitations" AS RESTRICTIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can read their own nonces" ON "nonces" AS PERMISSIVE FOR SELECT TO public USING ((user_id = ( SELECT auth.uid() AS uid)));--> statement-breakpoint
CREATE POLICY "notifications_read_self" ON "notifications" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((account_id = ( SELECT auth.uid() AS uid)) OR has_role_on_account(account_id)));--> statement-breakpoint
CREATE POLICY "notifications_update_self" ON "notifications" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "restrict_mfa_notifications" ON "notifications" AS RESTRICTIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "restrict_mfa_role_permissions" ON "role_permissions" AS RESTRICTIVE FOR ALL TO "authenticated" USING (is_mfa_compliant());--> statement-breakpoint
CREATE POLICY "role_permissions_read" ON "role_permissions" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "super_admins_access_role_permissions" ON "role_permissions" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "roles_read" ON "roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "accounts_memberships_delete" ON "accounts_memberships" AS PERMISSIVE FOR DELETE TO "authenticated" USING (((user_id = ( SELECT auth.uid() AS uid)) OR can_action_account_member(account_id, user_id)));--> statement-breakpoint
CREATE POLICY "accounts_memberships_read" ON "accounts_memberships" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "restrict_mfa_accounts_memberships" ON "accounts_memberships" AS RESTRICTIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "super_admins_access_accounts_memberships" ON "accounts_memberships" AS PERMISSIVE FOR SELECT TO "authenticated";
*/