create extension if not exists "unaccent" with schema "public";

create type "public"."invitation" as ("email" text, "role" character varying(50));

create type "public"."app_permissions" as enum ('roles.manage', 'settings.manage', 'members.manage', 'invites.manage');

create type "public"."notification_channel" as enum ('in_app', 'email');

create type "public"."notification_type" as enum ('info', 'warning', 'error');

create sequence "public"."invitations_id_seq";


  create table "public"."accounts" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "primary_owner_user_id" uuid not null default auth.uid(),
    "name" character varying(255) not null,
    "slug" text,
    "email" character varying(320),
    "is_personal_account" boolean not null default false,
    "updated_at" timestamp with time zone,
    "created_at" timestamp with time zone,
    "created_by" uuid,
    "updated_by" uuid,
    "picture_url" character varying(1000),
    "public_data" jsonb not null default '{}'::jsonb
      );


alter table "public"."accounts" enable row level security;


  create table "public"."accounts_memberships" (
    "user_id" uuid not null,
    "account_id" uuid not null,
    "account_role" character varying(50) not null,
    "created_at" timestamp with time zone not null default CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone not null default CURRENT_TIMESTAMP,
    "created_by" uuid,
    "updated_by" uuid
      );


alter table "public"."accounts_memberships" enable row level security;


  create table "public"."config" (
    "enable_team_accounts" boolean not null default true
      );


alter table "public"."config" enable row level security;


  create table "public"."invitations" (
    "id" integer not null default nextval('public.invitations_id_seq'::regclass),
    "email" character varying(255) not null,
    "account_id" uuid not null,
    "invited_by" uuid not null,
    "role" character varying(50) not null,
    "invite_token" character varying(255) not null,
    "created_at" timestamp with time zone not null default CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone not null default CURRENT_TIMESTAMP,
    "expires_at" timestamp with time zone not null default (CURRENT_TIMESTAMP + '7 days'::interval)
      );


alter table "public"."invitations" enable row level security;


  create table "public"."nonces" (
    "id" uuid not null default gen_random_uuid(),
    "client_token" text not null,
    "nonce" text not null,
    "user_id" uuid,
    "purpose" text not null,
    "expires_at" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "used_at" timestamp with time zone,
    "revoked" boolean not null default false,
    "revoked_reason" text,
    "verification_attempts" integer not null default 0,
    "last_verification_at" timestamp with time zone,
    "last_verification_ip" inet,
    "last_verification_user_agent" text,
    "metadata" jsonb default '{}'::jsonb,
    "scopes" text[] default '{}'::text[]
      );


alter table "public"."nonces" enable row level security;


  create table "public"."notifications" (
    "id" bigint generated always as identity not null,
    "account_id" uuid not null,
    "type" public.notification_type not null default 'info'::public.notification_type,
    "body" character varying(5000) not null,
    "link" character varying(255),
    "channel" public.notification_channel not null default 'in_app'::public.notification_channel,
    "dismissed" boolean not null default false,
    "expires_at" timestamp with time zone default (now() + '1 mon'::interval),
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."notifications" enable row level security;


  create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role" character varying(50) not null,
    "permission" public.app_permissions not null
      );


alter table "public"."role_permissions" enable row level security;


  create table "public"."roles" (
    "name" character varying(50) not null,
    "hierarchy_level" integer not null
      );


alter table "public"."roles" enable row level security;

alter sequence "public"."invitations_id_seq" owned by "public"."invitations"."id";

CREATE UNIQUE INDEX accounts_email_key ON public.accounts USING btree (email);

CREATE UNIQUE INDEX accounts_memberships_pkey ON public.accounts_memberships USING btree (user_id, account_id);

CREATE UNIQUE INDEX accounts_pkey ON public.accounts USING btree (id);

CREATE UNIQUE INDEX accounts_slug_key ON public.accounts USING btree (slug);

CREATE INDEX idx_nonces_status ON public.nonces USING btree (client_token, user_id, purpose, expires_at) WHERE ((used_at IS NULL) AND (revoked = false));

CREATE INDEX idx_nonces_verify_lookup ON public.nonces USING btree (purpose, expires_at DESC, user_id) WHERE ((used_at IS NULL) AND (revoked = false));

CREATE INDEX idx_notifications_account_dismissed ON public.notifications USING btree (account_id, dismissed, expires_at);

CREATE UNIQUE INDEX invitations_email_account_id_key ON public.invitations USING btree (email, account_id);

CREATE UNIQUE INDEX invitations_invite_token_key ON public.invitations USING btree (invite_token);

CREATE UNIQUE INDEX invitations_pkey ON public.invitations USING btree (id);

CREATE INDEX ix_accounts_is_personal_account ON public.accounts USING btree (is_personal_account);

CREATE INDEX ix_accounts_memberships_account_id ON public.accounts_memberships USING btree (account_id);

CREATE INDEX ix_accounts_memberships_account_role ON public.accounts_memberships USING btree (account_role);

CREATE INDEX ix_accounts_memberships_user_id ON public.accounts_memberships USING btree (user_id);

CREATE INDEX ix_accounts_primary_owner_user_id ON public.accounts USING btree (primary_owner_user_id);

CREATE INDEX ix_invitations_account_id ON public.invitations USING btree (account_id);

CREATE INDEX ix_role_permissions_role ON public.role_permissions USING btree (role);

CREATE UNIQUE INDEX nonces_pkey ON public.nonces USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);

CREATE UNIQUE INDEX role_permissions_role_permission_key ON public.role_permissions USING btree (role, permission);

CREATE UNIQUE INDEX roles_hierarchy_level_key ON public.roles USING btree (hierarchy_level);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (name);

CREATE UNIQUE INDEX unique_personal_account ON public.accounts USING btree (primary_owner_user_id) WHERE (is_personal_account = true);

alter table "public"."accounts" add constraint "accounts_pkey" PRIMARY KEY using index "accounts_pkey";

alter table "public"."accounts_memberships" add constraint "accounts_memberships_pkey" PRIMARY KEY using index "accounts_memberships_pkey";

alter table "public"."invitations" add constraint "invitations_pkey" PRIMARY KEY using index "invitations_pkey";

alter table "public"."nonces" add constraint "nonces_pkey" PRIMARY KEY using index "nonces_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."accounts" add constraint "accounts_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."accounts" validate constraint "accounts_created_by_fkey";

alter table "public"."accounts" add constraint "accounts_email_key" UNIQUE using index "accounts_email_key";

alter table "public"."accounts" add constraint "accounts_primary_owner_user_id_fkey" FOREIGN KEY (primary_owner_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."accounts" validate constraint "accounts_primary_owner_user_id_fkey";

alter table "public"."accounts" add constraint "accounts_slug_key" UNIQUE using index "accounts_slug_key";

alter table "public"."accounts" add constraint "accounts_slug_null_if_personal_account_true" CHECK ((((is_personal_account = true) AND (slug IS NULL)) OR ((is_personal_account = false) AND (slug IS NOT NULL)))) not valid;

alter table "public"."accounts" validate constraint "accounts_slug_null_if_personal_account_true";

alter table "public"."accounts" add constraint "accounts_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."accounts" validate constraint "accounts_updated_by_fkey";

alter table "public"."accounts_memberships" add constraint "accounts_memberships_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."accounts_memberships" validate constraint "accounts_memberships_account_id_fkey";

alter table "public"."accounts_memberships" add constraint "accounts_memberships_account_role_fkey" FOREIGN KEY (account_role) REFERENCES public.roles(name) not valid;

alter table "public"."accounts_memberships" validate constraint "accounts_memberships_account_role_fkey";

alter table "public"."accounts_memberships" add constraint "accounts_memberships_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."accounts_memberships" validate constraint "accounts_memberships_created_by_fkey";

alter table "public"."accounts_memberships" add constraint "accounts_memberships_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."accounts_memberships" validate constraint "accounts_memberships_updated_by_fkey";

alter table "public"."accounts_memberships" add constraint "accounts_memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."accounts_memberships" validate constraint "accounts_memberships_user_id_fkey";

alter table "public"."invitations" add constraint "invitations_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."invitations" validate constraint "invitations_account_id_fkey";

alter table "public"."invitations" add constraint "invitations_email_account_id_key" UNIQUE using index "invitations_email_account_id_key";

alter table "public"."invitations" add constraint "invitations_invite_token_key" UNIQUE using index "invitations_invite_token_key";

alter table "public"."invitations" add constraint "invitations_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."invitations" validate constraint "invitations_invited_by_fkey";

alter table "public"."invitations" add constraint "invitations_role_fkey" FOREIGN KEY (role) REFERENCES public.roles(name) not valid;

alter table "public"."invitations" validate constraint "invitations_role_fkey";

alter table "public"."nonces" add constraint "nonces_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."nonces" validate constraint "nonces_user_id_fkey";

alter table "public"."notifications" add constraint "notifications_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_account_id_fkey";

alter table "public"."role_permissions" add constraint "role_permissions_role_fkey" FOREIGN KEY (role) REFERENCES public.roles(name) not valid;

alter table "public"."role_permissions" validate constraint "role_permissions_role_fkey";

alter table "public"."role_permissions" add constraint "role_permissions_role_permission_key" UNIQUE using index "role_permissions_role_permission_key";

alter table "public"."roles" add constraint "roles_hierarchy_level_check" CHECK ((hierarchy_level > 0)) not valid;

alter table "public"."roles" validate constraint "roles_hierarchy_level_check";

alter table "public"."roles" add constraint "roles_hierarchy_level_key" UNIQUE using index "roles_hierarchy_level_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.accept_invitation(token text, user_id uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    target_account_id uuid;
    target_role varchar(50);
begin
    select
        account_id,
        role into target_account_id,
        target_role
    from
        public.invitations
    where
        invite_token = token
        and expires_at > now();

    if not found then
        raise exception 'Invalid or expired invitation token';
    end if;

    insert into public.accounts_memberships(
        user_id,
        account_id,
        account_role)
    values (
        accept_invitation.user_id,
        target_account_id,
        target_role);

    delete from public.invitations
    where invite_token = token;

    return target_account_id;
end;

$function$
;

CREATE OR REPLACE FUNCTION public.add_current_user_to_new_account()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    if new.primary_owner_user_id = auth.uid() then
        insert into public.accounts_memberships(
            account_id,
            user_id,
            account_role)
        values(
            new.id,
            auth.uid(),
            public.get_upper_system_role());

    end if;

    return NEW;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.add_invitations_to_account(account_slug text, invitations public.invitation[])
 RETURNS public.invitations[]
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    new_invitation public.invitations;
    all_invitations public.invitations[] := array[]::public.invitations[];
    invite_token text;
    email text;
    role varchar(50);
begin
    FOREACH email,
    role in array invitations loop
        invite_token := extensions.uuid_generate_v4();

        insert into public.invitations(
            email,
            account_id,
            invited_by,
            role,
            invite_token)
        values (
            email,
(
                select
                    id
                from
                    public.accounts
                where
                    slug = account_slug), auth.uid(), role, invite_token)
    returning
        * into new_invitation;

        all_invitations := array_append(all_invitations, new_invitation);

    end loop;

    return all_invitations;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.can_action_account_member(target_team_account_id uuid, target_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    permission_granted boolean;
    target_user_hierarchy_level int;
    current_user_hierarchy_level int;
    is_account_owner boolean;
    target_user_role varchar(50);
begin
    if target_user_id = auth.uid() then
      raise exception 'You cannot update your own account membership with this function';
    end if;

    -- an account owner can action any member of the account
    if public.is_account_owner(target_team_account_id) then
      return true;
    end if;

     -- check the target user is the primary owner of the account
    select
        exists (
            select
                1
            from
                public.accounts
            where
                id = target_team_account_id
                and primary_owner_user_id = target_user_id) into is_account_owner;

    if is_account_owner then
        raise exception 'The primary account owner cannot be actioned';
    end if;

    -- validate the auth user has the required permission on the account
    -- to manage members of the account
    select
 public.has_permission(auth.uid(), target_team_account_id,
     'members.manage'::public.app_permissions) into
     permission_granted;

    -- if the user does not have the required permission, raise an exception
    if not permission_granted then
      raise exception 'You do not have permission to action a member from this account';
    end if;

    -- get the role of the target user
    select
        am.account_role,
        r.hierarchy_level
    from
        public.accounts_memberships as am
    join
        public.roles as r on am.account_role = r.name
    where
        am.account_id = target_team_account_id
        and am.user_id = target_user_id
    into target_user_role, target_user_hierarchy_level;

    -- get the hierarchy level of the current user
    select
        r.hierarchy_level into current_user_hierarchy_level
    from
        public.roles as r
    join
        public.accounts_memberships as am on r.name = am.account_role
    where
        am.account_id = target_team_account_id
        and am.user_id = auth.uid();

    if target_user_role is null then
      raise exception 'The target user does not have a role on the account';
    end if;

    if current_user_hierarchy_level is null then
      raise exception 'The current user does not have a role on the account';
    end if;

    -- check the current user has a higher role than the target user
    if current_user_hierarchy_level >= target_user_hierarchy_level then
      raise exception 'You do not have permission to action a member from this account';
    end if;

    return true;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.check_team_account()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if(
        select
            is_personal_account
        from
            public.accounts
        where
            id = new.account_id) then
        raise exception 'Account must be an team account';

    end if;

    return NEW;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.cleanup_expired_nonces(p_older_than_days integer DEFAULT 1, p_include_used boolean DEFAULT true, p_include_revoked boolean DEFAULT true)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_count INTEGER;
BEGIN
  -- Count and delete expired or used nonces based on parameters
  WITH deleted AS (
    DELETE FROM public.nonces
    WHERE
      (
        -- Expired and unused tokens
        (expires_at < NOW() AND used_at IS NULL)

        -- Used tokens older than specified days (if enabled)
        OR (p_include_used = TRUE AND used_at < NOW() - (p_older_than_days * interval '1 day'))

        -- Revoked tokens older than specified days (if enabled)
        OR (p_include_revoked = TRUE AND revoked = TRUE AND created_at < NOW() - (p_older_than_days * interval '1 day'))
      )
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_count FROM deleted;

  RETURN v_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_invitation(account_id uuid, email text, role character varying)
 RETURNS public.invitations
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    new_invitation public.invitations;
    invite_token text;
begin
    invite_token := extensions.uuid_generate_v4();

    insert into public.invitations(
        email,
        account_id,
        invited_by,
        role,
        invite_token)
    values (
        email,
        account_id,
        auth.uid(),
        role,
        invite_token)
returning
    * into new_invitation;

    return new_invitation;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.create_nonce(p_user_id uuid DEFAULT NULL::uuid, p_purpose text DEFAULT NULL::text, p_expires_in_seconds integer DEFAULT 3600, p_metadata jsonb DEFAULT NULL::jsonb, p_scopes text[] DEFAULT NULL::text[], p_revoke_previous boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
    v_client_token TEXT;
    v_nonce TEXT;
    v_expires_at TIMESTAMPTZ;
    v_id UUID;
    v_plaintext_token TEXT;
    v_revoked_count INTEGER;
BEGIN
    -- Revoke previous tokens for the same user and purpose if requested
    -- This only applies if a user ID is provided (not for anonymous tokens)
    IF p_revoke_previous = TRUE AND p_user_id IS NOT NULL THEN
        WITH revoked AS (
            UPDATE public.nonces
                SET
                    revoked = TRUE,
                    revoked_reason = 'Superseded by new token with same purpose'
                WHERE
                    user_id = p_user_id
                        AND purpose = p_purpose
                        AND used_at IS NULL
                        AND revoked = FALSE
                        AND expires_at > NOW()
                RETURNING 1
        )
        SELECT COUNT(*) INTO v_revoked_count FROM revoked;
    END IF;

    -- Generate a 6-digit token
    v_plaintext_token := (100000 + floor(random() * 900000))::text;
    v_client_token := extensions.crypt(v_plaintext_token, extensions.gen_salt('bf'));

    -- Still generate a secure nonce for internal use
    v_nonce := encode(extensions.gen_random_bytes(24), 'base64');
    v_nonce := extensions.crypt(v_nonce, extensions.gen_salt('bf'));

    -- Calculate expiration time
    v_expires_at := NOW() + (p_expires_in_seconds * interval '1 second');

    -- Insert the new nonce
    INSERT INTO public.nonces (
        client_token,
        nonce,
        user_id,
        expires_at,
        metadata,
        purpose,
        scopes
    )
    VALUES (
               v_client_token,
               v_nonce,
               p_user_id,
               v_expires_at,
               COALESCE(p_metadata, '{}'::JSONB),
               p_purpose,
               COALESCE(p_scopes, '{}'::TEXT[])
           )
    RETURNING id INTO v_id;

    -- Return the token information
    -- Note: returning the plaintext token, not the hash
    RETURN jsonb_build_object(
            'id', v_id,
            'token', v_plaintext_token,
            'expires_at', v_expires_at,
            'revoked_previous_count', COALESCE(v_revoked_count, 0)
           );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_team_account(account_name text)
 RETURNS public.accounts
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    new_account public.accounts;
begin
    if (not public.is_set('enable_team_accounts')) then
        raise exception 'Team accounts are not enabled';
    end if;

    insert into public.accounts(
        name,
        is_personal_account)
    values (
        account_name,
        false)
returning
    * into new_account;

    return new_account;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.get_account_invitations(account_slug text)
 RETURNS TABLE(id integer, email character varying, account_id uuid, invited_by uuid, role character varying, created_at timestamp with time zone, updated_at timestamp with time zone, expires_at timestamp with time zone, inviter_name character varying, inviter_email character varying)
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    return query
    select
        invitation.id,
        invitation.email,
        invitation.account_id,
        invitation.invited_by,
        invitation.role,
        invitation.created_at,
        invitation.updated_at,
        invitation.expires_at,
        account.name,
        account.email
    from
        public.invitations as invitation
        join public.accounts as account on invitation.account_id = account.id
    where
        account.slug = account_slug;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.get_account_members(account_slug text)
 RETURNS TABLE(id uuid, user_id uuid, account_id uuid, role character varying, role_hierarchy_level integer, primary_owner_user_id uuid, name character varying, email character varying, picture_url character varying, created_at timestamp with time zone, updated_at timestamp with time zone)
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    return QUERY
    select
        acc.id,
        am.user_id,
        am.account_id,
        am.account_role,
        r.hierarchy_level,
        a.primary_owner_user_id,
        acc.name,
        acc.email,
        acc.picture_url,
        am.created_at,
        am.updated_at
    from
        public.accounts_memberships am
        join public.accounts a on a.id = am.account_id
        join public.accounts acc on acc.id = am.user_id
        join public.roles r on r.name = am.account_role
    where
        a.slug = account_slug;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.get_config()
 RETURNS json
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    result record;
begin
    select
        *
    from
        public.config
    limit 1 into result;

    return row_to_json(result);

end;

$function$
;

CREATE OR REPLACE FUNCTION public.get_nonce_status(p_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_nonce public.nonces;
BEGIN
  SELECT * INTO v_nonce FROM public.nonces WHERE id = p_id;

  IF v_nonce.id IS NULL THEN
    RETURN jsonb_build_object('exists', false);
  END IF;

  RETURN jsonb_build_object(
    'exists', true,
    'purpose', v_nonce.purpose,
    'user_id', v_nonce.user_id,
    'created_at', v_nonce.created_at,
    'expires_at', v_nonce.expires_at,
    'used_at', v_nonce.used_at,
    'revoked', v_nonce.revoked,
    'revoked_reason', v_nonce.revoked_reason,
    'verification_attempts', v_nonce.verification_attempts,
    'last_verification_at', v_nonce.last_verification_at,
    'last_verification_ip', v_nonce.last_verification_ip,
    'is_valid', (v_nonce.used_at IS NULL AND NOT v_nonce.revoked AND v_nonce.expires_at > NOW())
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_storage_filename_as_uuid(name text)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    return replace(storage.filename(name), concat('.',
	storage.extension(name)), '')::uuid;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.get_upper_system_role()
 RETURNS character varying
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    role varchar(50);
begin
    select name from public.roles
      where hierarchy_level = 1 into role;

    return role;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_update_user_email()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    update
        public.accounts
    set
        email = new.email
    where
        primary_owner_user_id = new.id
        and is_personal_account = true;

    return new;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.has_more_elevated_role(target_user_id uuid, target_account_id uuid, role_name character varying)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    declare is_primary_owner boolean;
    user_role_hierarchy_level int;
    target_role_hierarchy_level int;
begin
    -- Check if the user is the primary owner of the account
    select
        exists (
            select
                1
            from
                public.accounts
            where
                id = target_account_id
                and primary_owner_user_id = target_user_id) into is_primary_owner;

    -- If the user is the primary owner, they have the highest role and can
    --   perform any action
    if is_primary_owner then
        return true;
    end if;

    -- Get the hierarchy level of the user's role within the account
    select
        hierarchy_level into user_role_hierarchy_level
    from
        public.roles
    where
        name =(
            select
                account_role
            from
                public.accounts_memberships
            where
                account_id = target_account_id
                and target_user_id = user_id);

    if user_role_hierarchy_level is null then
        return false;
    end if;

    -- Get the hierarchy level of the target role
    select
        hierarchy_level into target_role_hierarchy_level
    from
        public.roles
    where
        name = role_name;

    -- If the target role does not exist, the user cannot perform the action
    if target_role_hierarchy_level is null then
        return false;
    end if;

    -- If the user's role is higher than the target role, they can perform
    --   the action
    return user_role_hierarchy_level < target_role_hierarchy_level;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.has_permission(user_id uuid, account_id uuid, permission_name public.app_permissions)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    return exists(
        select
            1
        from
            public.accounts_memberships
	    join public.role_permissions on
		accounts_memberships.account_role =
		role_permissions.role
        where
            accounts_memberships.user_id = has_permission.user_id
            and accounts_memberships.account_id = has_permission.account_id
            and role_permissions.permission = has_permission.permission_name);

end;

$function$
;

CREATE OR REPLACE FUNCTION public.has_role_on_account(account_id uuid, account_role character varying DEFAULT NULL::character varying)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
    select
        exists(
            select
                1
            from
                public.accounts_memberships membership
            where
                membership.user_id = (select auth.uid())
                and membership.account_id = has_role_on_account.account_id
                and((membership.account_role = has_role_on_account.account_role
                    or has_role_on_account.account_role is null)));
$function$
;

CREATE OR REPLACE FUNCTION public.has_same_role_hierarchy_level(target_user_id uuid, target_account_id uuid, role_name character varying)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    is_primary_owner boolean;
    user_role_hierarchy_level int;
    target_role_hierarchy_level int;
begin
    -- Check if the user is the primary owner of the account
    select
        exists (
            select
                1
            from
                public.accounts
            where
                id = target_account_id
                and primary_owner_user_id = target_user_id) into is_primary_owner;

    -- If the user is the primary owner, they have the highest role and can perform any action
    if is_primary_owner then
        return true;
    end if;

    -- Get the hierarchy level of the user's role within the account
    select
        hierarchy_level into user_role_hierarchy_level
    from
        public.roles
    where
        name =(
            select
                account_role
            from
                public.accounts_memberships
            where
                account_id = target_account_id
                and target_user_id = user_id);

    -- If the user does not have a role in the account, they cannot perform the action
    if user_role_hierarchy_level is null then
        return false;
    end if;

    -- Get the hierarchy level of the target role
    select
        hierarchy_level into target_role_hierarchy_level
    from
        public.roles
    where
        name = role_name;

    -- If the target role does not exist, the user cannot perform the action
    if target_role_hierarchy_level is null then
        return false;
    end if;

   -- check the user's role hierarchy level is the same as the target role
    return user_role_hierarchy_level = target_role_hierarchy_level;

end;

$function$
;


CREATE OR REPLACE FUNCTION public.is_aal2()
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    is_aal2 boolean;
begin
    select auth.jwt() ->> 'aal' = 'aal2' into is_aal2;

    return coalesce(is_aal2, false);
end
$function$
;

CREATE OR REPLACE FUNCTION public.is_account_owner(account_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SET search_path TO ''
AS $function$
    select
        exists(
            select
                1
            from
                public.accounts
            where
                id = is_account_owner.account_id
                and primary_owner_user_id = auth.uid());
$function$
;

CREATE OR REPLACE FUNCTION public.is_account_team_member(target_account_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SET search_path TO ''
AS $function$
    select exists(
        select 1
        from public.accounts_memberships as membership
        where public.is_team_member (membership.account_id, target_account_id)
    );
$function$
;

CREATE OR REPLACE FUNCTION public.is_mfa_compliant()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    return array[(select auth.jwt()->>'aal')] <@ (
        select
            case
                when count(id) > 0 then array['aal2']
                else array['aal1', 'aal2']
                end as aal
        from auth.mfa_factors
        where ((select auth.uid()) = auth.mfa_factors.user_id) and auth.mfa_factors.status = 'verified'
    );
end
$function$
;

CREATE OR REPLACE FUNCTION public.is_set(field_name text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    result boolean;
begin
    execute format('select %I from public.config limit 1', field_name) into result;

    return result;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.is_super_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
    is_super_admin boolean;
begin
    if not public.is_aal2() then
        return false;
    end if;

    select (auth.jwt() ->> 'app_metadata')::jsonb ->> 'role' = 'super-admin' into is_super_admin;

    return coalesce(is_super_admin, false);
end
$function$
;

CREATE OR REPLACE FUNCTION public.is_team_member(account_id uuid, user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
    select
        exists(
            select
                1
            from
                public.accounts_memberships membership
            where
                public.has_role_on_account(account_id)
                and membership.user_id = is_team_member.user_id
                and membership.account_id = is_team_member.account_id);
$function$
;

CREATE OR REPLACE FUNCTION public.prevent_account_owner_membership_delete()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if exists(
        select
            1
        from
            public.accounts
        where
            id = old.account_id
            and primary_owner_user_id = old.user_id) then
    raise exception 'The primary account owner cannot be removed from the account membership list';

end if;

    return old;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.prevent_memberships_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if new.account_role <> old.account_role then
        return new;
    end if;

    raise exception 'Only the account_role can be updated';

end; $function$
;

CREATE OR REPLACE FUNCTION public.protect_account_fields()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if current_user in('authenticated', 'anon') then
	if new.id <> old.id or new.is_personal_account <>
	    old.is_personal_account or new.primary_owner_user_id <>
	    old.primary_owner_user_id or new.email <> old.email then
            raise exception 'You do not have permission to update this field';

        end if;

    end if;

    return NEW;

end
$function$
;

CREATE OR REPLACE FUNCTION public.revoke_nonce(p_id uuid, p_reason text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_affected_rows INTEGER;
BEGIN
  UPDATE public.nonces
  SET
    revoked = TRUE,
    revoked_reason = p_reason
  WHERE
    id = p_id
    AND used_at IS NULL
    AND NOT revoked
  RETURNING 1 INTO v_affected_rows;

  RETURN v_affected_rows > 0;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_slug_from_account_name()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    sql_string varchar;
    tmp_slug varchar;
    increment integer;
    tmp_row record;
    tmp_row_count integer;
begin
    tmp_row_count = 1;

    increment = 0;

    while tmp_row_count > 0 loop
        if increment > 0 then
            tmp_slug = public.slugify(new.name || ' ' || increment::varchar);

        else
            tmp_slug = public.slugify(new.name);

        end if;

	sql_string = format('select count(1) cnt from public.accounts where slug = ''' || tmp_slug ||
	    '''; ');

        for tmp_row in execute (sql_string)
            loop
                raise notice 'tmp_row %', tmp_row;

                tmp_row_count = tmp_row.cnt;

            end loop;

        increment = increment +1;

    end loop;

    new.slug := tmp_slug;

    return NEW;

end
$function$
;

CREATE OR REPLACE FUNCTION public.setup_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    user_name text;
    picture_url text;
begin
    if new.raw_user_meta_data ->> 'name' is not null then
        user_name := new.raw_user_meta_data ->> 'name';

    end if;

    if user_name is null and new.email is not null then
        user_name := split_part(new.email, '@', 1);

    end if;

    if user_name is null then
        user_name := '';

    end if;

    if new.raw_user_meta_data ->> 'avatar_url' is not null then
        picture_url := new.raw_user_meta_data ->> 'avatar_url';
    else
        picture_url := null;
    end if;

    insert into public.accounts(
        id,
        primary_owner_user_id,
        name,
        is_personal_account,
        picture_url,
        email)
    values (
        new.id,
        new.id,
        user_name,
        true,
        picture_url,
        new.email);

    return new;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.slugify(value text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE STRICT
 SET search_path TO ''
AS $function$
    -- removes accents (diacritic signs) from a given string --
    with "unaccented" as(
        select
            public.unaccent("value") as "value"
),
-- lowercases the string
"lowercase" as(
    select
        lower("value") as "value"
    from
        "unaccented"
),
-- remove single and double quotes
"removed_quotes" as(
    select
	regexp_replace("value", '[''"]+', '',
	    'gi') as "value"
    from
        "lowercase"
),
-- replaces anything that's not a letter, number, hyphen('-'), or underscore('_') with a hyphen('-')
"hyphenated" as(
    select
	regexp_replace("value", '[^a-z0-9\\-_]+', '-',
	    'gi') as "value"
    from
        "removed_quotes"
),
-- trims hyphens('-') if they exist on the head or tail of
--   the string
"trimmed" as(
    select
	regexp_replace(regexp_replace("value", '\-+$',
	    ''), '^\-', '') as "value" from "hyphenated"
)
        select
            "value"
        from
            "trimmed";
$function$
;

CREATE OR REPLACE FUNCTION public.team_account_workspace(account_slug text)
 RETURNS TABLE(id uuid, name character varying, picture_url character varying, slug text, role character varying, role_hierarchy_level integer, primary_owner_user_id uuid, permissions public.app_permissions[])
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    return QUERY
    select
        accounts.id,
        accounts.name,
        accounts.picture_url,
        accounts.slug,
        accounts_memberships.account_role,
        roles.hierarchy_level,
        accounts.primary_owner_user_id,
        array_agg(role_permissions.permission)
    from
        public.accounts
        join public.accounts_memberships on accounts.id = accounts_memberships.account_id
        join public.roles on accounts_memberships.account_role = roles.name
        left join public.role_permissions on accounts_memberships.account_role = role_permissions.role
    where
        accounts.slug = account_slug
        and public.accounts_memberships.user_id = (select auth.uid())
    group by
        accounts.id,
        accounts_memberships.account_role,
        roles.hierarchy_level;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.transfer_team_account_ownership(target_account_id uuid, new_owner_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if current_user not in('service_role') then
        raise exception 'You do not have permission to transfer account ownership';
    end if;

    -- verify the user is already a member of the account
    if not exists(
        select
            1
        from
            public.accounts_memberships
        where
            target_account_id = account_id
            and user_id = new_owner_id) then
        raise exception 'The new owner must be a member of the account';
    end if;

    -- update the primary owner of the account
    update
        public.accounts
    set
        primary_owner_user_id = new_owner_id
    where
        id = target_account_id
        and is_personal_account = false;

    -- update membership assigning it the hierarchy role
    update
        public.accounts_memberships
    set
        account_role =(
            public.get_upper_system_role())
    where
        target_account_id = account_id
        and user_id = new_owner_id
        and account_role <>(
            public.get_upper_system_role());

end;

$function$
;

CREATE OR REPLACE FUNCTION public.trigger_set_timestamps()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if TG_OP = 'INSERT' then
        new.created_at = now();

        new.updated_at = now();

    else
        new.updated_at = now();

        new.created_at = old.created_at;

    end if;

    return NEW;

end
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_set_user_tracking()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if TG_OP = 'INSERT' then
        new.created_by = auth.uid();
        new.updated_by = auth.uid();

    else
        new.updated_by = auth.uid();

        new.created_by = old.created_by;

    end if;

    return NEW;

end
$function$
;

CREATE OR REPLACE FUNCTION public.update_notification_dismissed_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    old.dismissed := new.dismissed;

    if (new is distinct from old) then
         raise exception 'UPDATE of columns other than "dismissed" is forbidden';
    end if;

    return old;
end;
$function$
;

create or replace view "public"."user_account_workspace" as  SELECT id,
    name,
    picture_url
   FROM public.accounts
  WHERE ((primary_owner_user_id = ( SELECT auth.uid() AS uid)) AND (is_personal_account = true))
 LIMIT 1;


create or replace view "public"."user_accounts" as  SELECT account.id,
    account.name,
    account.picture_url,
    account.slug,
    membership.account_role AS role
   FROM (public.accounts account
     JOIN public.accounts_memberships membership ON ((account.id = membership.account_id)))
  WHERE ((membership.user_id = ( SELECT auth.uid() AS uid)) AND (account.is_personal_account = false) AND (account.id IN ( SELECT accounts_memberships.account_id
           FROM public.accounts_memberships
          WHERE (accounts_memberships.user_id = ( SELECT auth.uid() AS uid)))));


CREATE OR REPLACE FUNCTION public.verify_nonce(p_token text, p_purpose text, p_user_id uuid DEFAULT NULL::uuid, p_required_scopes text[] DEFAULT NULL::text[], p_max_verification_attempts integer DEFAULT 5, p_ip inet DEFAULT NULL::inet, p_user_agent text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
    v_nonce          RECORD;
BEGIN
    -- Find and update the nonce in a single operation
    -- First filter by indexed columns to reduce candidate rows, then do bcrypt comparison
    WITH candidate_nonces AS (
        -- Use index to filter candidates by purpose, user_id, expiry, status
        SELECT id, client_token, user_id, purpose, metadata, scopes,
               verification_attempts, expires_at, used_at, revoked
        FROM public.nonces
        WHERE purpose = p_purpose
          AND used_at IS NULL
          AND NOT revoked
          AND expires_at > NOW()
          -- Only apply user_id filter if the token was created for a specific user
          AND (
            -- Case 1: Anonymous token (user_id is NULL in DB)
            (user_id IS NULL)
                OR
                -- Case 2: User-specific token (check if user_id matches)
            (user_id = p_user_id)
          )
        ORDER BY created_at DESC
        -- Safety net: Limit to 100 most recent candidates to cap worst-case performance
        -- In production, auto-revocation keeps this low, but this protects against edge cases
        LIMIT 100
        -- CRITICAL: Lock rows to prevent race conditions in concurrent verifications
        -- SKIP LOCKED ensures other requests fail fast instead of waiting
        FOR UPDATE SKIP LOCKED
    ),
    matched_nonce AS (
        -- Now do the expensive bcrypt comparison only on filtered candidates
        SELECT *
        FROM candidate_nonces
        WHERE client_token = extensions.crypt(p_token, client_token)
        LIMIT 1
    ),
    updated_nonce AS (
        -- Update only the matched nonce
        UPDATE public.nonces
        SET verification_attempts        = verification_attempts + 1,
            last_verification_at         = NOW(),
            last_verification_ip         = COALESCE(p_ip, last_verification_ip),
            last_verification_user_agent = COALESCE(p_user_agent, last_verification_user_agent)
        WHERE id = (SELECT id FROM matched_nonce)
        RETURNING *
    )
    SELECT * INTO v_nonce FROM updated_nonce;

    -- Check if nonce exists
    IF v_nonce.id IS NULL THEN
        RETURN jsonb_build_object(
                'valid', false,
                'message', 'Invalid or expired token'
               );
    END IF;

    -- Check if max verification attempts exceeded (using the incremented value)
    IF p_max_verification_attempts > 0 AND v_nonce.verification_attempts > p_max_verification_attempts THEN
        -- Automatically revoke the token
        UPDATE public.nonces
        SET revoked        = TRUE,
            revoked_reason = 'Maximum verification attempts exceeded'
        WHERE id = v_nonce.id;

        RETURN jsonb_build_object(
                'valid', false,
                'message', 'Token revoked due to too many verification attempts',
                'max_attempts_exceeded', true
               );
    END IF;

    -- Check scopes if required
    IF p_required_scopes IS NOT NULL AND array_length(p_required_scopes, 1) > 0 THEN
        -- Fix scope validation to properly check if token scopes contain all required scopes
        -- Using array containment check: array1 @> array2 (array1 contains array2)
        IF NOT (v_nonce.scopes @> p_required_scopes) THEN
            RETURN jsonb_build_object(
                    'valid', false,
                    'message', 'Token does not have required permissions',
                    'token_scopes', v_nonce.scopes,
                    'required_scopes', p_required_scopes
                   );
        END IF;
    END IF;

    -- Mark nonce as used
    UPDATE public.nonces
    SET used_at = NOW()
    WHERE id = v_nonce.id;

    -- Return success with metadata
    RETURN jsonb_build_object(
            'valid', true,
            'user_id', v_nonce.user_id,
            'metadata', v_nonce.metadata,
            'scopes', v_nonce.scopes,
            'purpose', v_nonce.purpose
           );
END;
$function$
;

grant delete on table "public"."accounts" to "anon";

grant insert on table "public"."accounts" to "anon";

grant references on table "public"."accounts" to "anon";

grant select on table "public"."accounts" to "anon";

grant trigger on table "public"."accounts" to "anon";

grant truncate on table "public"."accounts" to "anon";

grant update on table "public"."accounts" to "anon";

grant delete on table "public"."accounts" to "authenticated";

grant insert on table "public"."accounts" to "authenticated";

grant select on table "public"."accounts" to "authenticated";

grant update on table "public"."accounts" to "authenticated";

grant delete on table "public"."accounts" to "service_role";

grant insert on table "public"."accounts" to "service_role";

grant select on table "public"."accounts" to "service_role";

grant update on table "public"."accounts" to "service_role";

grant delete on table "public"."accounts_memberships" to "anon";

grant insert on table "public"."accounts_memberships" to "anon";

grant references on table "public"."accounts_memberships" to "anon";

grant select on table "public"."accounts_memberships" to "anon";

grant trigger on table "public"."accounts_memberships" to "anon";

grant truncate on table "public"."accounts_memberships" to "anon";

grant update on table "public"."accounts_memberships" to "anon";

grant delete on table "public"."accounts_memberships" to "authenticated";

grant insert on table "public"."accounts_memberships" to "authenticated";

grant select on table "public"."accounts_memberships" to "authenticated";

grant update on table "public"."accounts_memberships" to "authenticated";

grant delete on table "public"."accounts_memberships" to "service_role";

grant insert on table "public"."accounts_memberships" to "service_role";

grant select on table "public"."accounts_memberships" to "service_role";

grant update on table "public"."accounts_memberships" to "service_role";

grant delete on table "public"."config" to "anon";

grant insert on table "public"."config" to "anon";

grant references on table "public"."config" to "anon";

grant select on table "public"."config" to "anon";

grant trigger on table "public"."config" to "anon";

grant truncate on table "public"."config" to "anon";

grant update on table "public"."config" to "anon";

grant select on table "public"."config" to "authenticated";

grant select on table "public"."config" to "service_role";

grant delete on table "public"."invitations" to "anon";

grant insert on table "public"."invitations" to "anon";

grant references on table "public"."invitations" to "anon";

grant select on table "public"."invitations" to "anon";

grant trigger on table "public"."invitations" to "anon";

grant truncate on table "public"."invitations" to "anon";

grant update on table "public"."invitations" to "anon";

grant delete on table "public"."invitations" to "authenticated";

grant insert on table "public"."invitations" to "authenticated";

grant select on table "public"."invitations" to "authenticated";

grant update on table "public"."invitations" to "authenticated";

grant delete on table "public"."invitations" to "service_role";

grant insert on table "public"."invitations" to "service_role";

grant select on table "public"."invitations" to "service_role";

grant update on table "public"."invitations" to "service_role";

grant delete on table "public"."nonces" to "anon";

grant insert on table "public"."nonces" to "anon";

grant references on table "public"."nonces" to "anon";

grant select on table "public"."nonces" to "anon";

grant trigger on table "public"."nonces" to "anon";

grant truncate on table "public"."nonces" to "anon";

grant update on table "public"."nonces" to "anon";

grant delete on table "public"."nonces" to "authenticated";

grant insert on table "public"."nonces" to "authenticated";

grant references on table "public"."nonces" to "authenticated";

grant select on table "public"."nonces" to "authenticated";

grant trigger on table "public"."nonces" to "authenticated";

grant truncate on table "public"."nonces" to "authenticated";

grant update on table "public"."nonces" to "authenticated";

grant delete on table "public"."nonces" to "service_role";

grant insert on table "public"."nonces" to "service_role";

grant references on table "public"."nonces" to "service_role";

grant select on table "public"."nonces" to "service_role";

grant trigger on table "public"."nonces" to "service_role";

grant truncate on table "public"."nonces" to "service_role";

grant update on table "public"."nonces" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."role_permissions" to "anon";

grant insert on table "public"."role_permissions" to "anon";

grant references on table "public"."role_permissions" to "anon";

grant select on table "public"."role_permissions" to "anon";

grant trigger on table "public"."role_permissions" to "anon";

grant truncate on table "public"."role_permissions" to "anon";

grant update on table "public"."role_permissions" to "anon";

grant select on table "public"."role_permissions" to "authenticated";

grant delete on table "public"."role_permissions" to "service_role";

grant insert on table "public"."role_permissions" to "service_role";

grant select on table "public"."role_permissions" to "service_role";

grant update on table "public"."role_permissions" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant select on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "service_role";


  create policy "accounts_read"
  on "public"."accounts"
  as permissive
  for select
  to authenticated
using (((( SELECT auth.uid() AS uid) = primary_owner_user_id) OR public.has_role_on_account(id) OR public.is_account_team_member(id)));



  create policy "accounts_self_update"
  on "public"."accounts"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = primary_owner_user_id))
with check ((( SELECT auth.uid() AS uid) = primary_owner_user_id));



  create policy "create_org_account"
  on "public"."accounts"
  as permissive
  for insert
  to authenticated
with check ((public.is_set('enable_team_accounts'::text) AND (is_personal_account = false)));



  create policy "delete_team_account"
  on "public"."accounts"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = primary_owner_user_id));



  create policy "restrict_mfa_accounts"
  on "public"."accounts"
  as restrictive
  for all
  to authenticated
using (public.is_mfa_compliant());



  create policy "super_admins_access_accounts"
  on "public"."accounts"
  as permissive
  for select
  to authenticated
using (public.is_super_admin());



  create policy "accounts_memberships_delete"
  on "public"."accounts_memberships"
  as permissive
  for delete
  to authenticated
using (((user_id = ( SELECT auth.uid() AS uid)) OR public.can_action_account_member(account_id, user_id)));



  create policy "accounts_memberships_read"
  on "public"."accounts_memberships"
  as permissive
  for select
  to authenticated
using (((( SELECT auth.uid() AS uid) = user_id) OR public.is_team_member(account_id, user_id)));



  create policy "restrict_mfa_accounts_memberships"
  on "public"."accounts_memberships"
  as restrictive
  for all
  to authenticated
using (public.is_mfa_compliant());



  create policy "super_admins_access_accounts_memberships"
  on "public"."accounts_memberships"
  as permissive
  for select
  to authenticated
using (public.is_super_admin());



  create policy "public config can be read by authenticated users"
  on "public"."config"
  as permissive
  for select
  to authenticated
using (true);



  create policy "invitations_create_self"
  on "public"."invitations"
  as permissive
  for insert
  to authenticated
with check ((public.is_set('enable_team_accounts'::text) AND public.has_permission(( SELECT auth.uid() AS uid), account_id, 'invites.manage'::public.app_permissions) AND (public.has_more_elevated_role(( SELECT auth.uid() AS uid), account_id, role) OR public.has_same_role_hierarchy_level(( SELECT auth.uid() AS uid), account_id, role))));



  create policy "invitations_delete"
  on "public"."invitations"
  as permissive
  for delete
  to authenticated
using ((public.has_role_on_account(account_id) AND public.has_permission(( SELECT auth.uid() AS uid), account_id, 'invites.manage'::public.app_permissions)));



  create policy "invitations_read_self"
  on "public"."invitations"
  as permissive
  for select
  to authenticated
using (public.has_role_on_account(account_id));



  create policy "invitations_update"
  on "public"."invitations"
  as permissive
  for update
  to authenticated
using ((public.has_permission(( SELECT auth.uid() AS uid), account_id, 'invites.manage'::public.app_permissions) AND public.has_more_elevated_role(( SELECT auth.uid() AS uid), account_id, role)))
with check ((public.has_permission(( SELECT auth.uid() AS uid), account_id, 'invites.manage'::public.app_permissions) AND public.has_more_elevated_role(( SELECT auth.uid() AS uid), account_id, role)));



  create policy "restrict_mfa_invitations"
  on "public"."invitations"
  as restrictive
  for all
  to authenticated
using (public.is_mfa_compliant());



  create policy "super_admins_access_invitations"
  on "public"."invitations"
  as permissive
  for select
  to authenticated
using (public.is_super_admin());



  create policy "Users can read their own nonces"
  on "public"."nonces"
  as permissive
  for select
  to public
using ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "notifications_read_self"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using (((account_id = ( SELECT auth.uid() AS uid)) OR public.has_role_on_account(account_id)));



  create policy "notifications_update_self"
  on "public"."notifications"
  as permissive
  for update
  to authenticated
using (((account_id = ( SELECT auth.uid() AS uid)) OR public.has_role_on_account(account_id)));



  create policy "restrict_mfa_notifications"
  on "public"."notifications"
  as restrictive
  for all
  to authenticated
using (public.is_mfa_compliant());



  create policy "restrict_mfa_role_permissions"
  on "public"."role_permissions"
  as restrictive
  for all
  to authenticated
using (public.is_mfa_compliant());



  create policy "role_permissions_read"
  on "public"."role_permissions"
  as permissive
  for select
  to authenticated
using (true);



  create policy "super_admins_access_role_permissions"
  on "public"."role_permissions"
  as permissive
  for select
  to authenticated
using (public.is_super_admin());



  create policy "roles_read"
  on "public"."roles"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER accounts_set_timestamps BEFORE INSERT OR UPDATE ON public.accounts FOR EACH ROW EXECUTE FUNCTION public.trigger_set_timestamps();

CREATE TRIGGER accounts_set_user_tracking BEFORE INSERT OR UPDATE ON public.accounts FOR EACH ROW EXECUTE FUNCTION public.trigger_set_user_tracking();

CREATE TRIGGER add_current_user_to_new_account AFTER INSERT ON public.accounts FOR EACH ROW WHEN ((new.is_personal_account = false)) EXECUTE FUNCTION public.add_current_user_to_new_account();

CREATE TRIGGER protect_account_fields BEFORE UPDATE ON public.accounts FOR EACH ROW EXECUTE FUNCTION public.protect_account_fields();

CREATE TRIGGER set_slug_from_account_name BEFORE INSERT ON public.accounts FOR EACH ROW WHEN (((new.name IS NOT NULL) AND (new.slug IS NULL) AND (new.is_personal_account = false))) EXECUTE FUNCTION public.set_slug_from_account_name();

CREATE TRIGGER update_slug_from_account_name BEFORE UPDATE ON public.accounts FOR EACH ROW WHEN (((new.name IS NOT NULL) AND ((new.name)::text <> (old.name)::text) AND (new.is_personal_account = false))) EXECUTE FUNCTION public.set_slug_from_account_name();

CREATE TRIGGER accounts_memberships_set_timestamps BEFORE INSERT OR UPDATE ON public.accounts_memberships FOR EACH ROW EXECUTE FUNCTION public.trigger_set_timestamps();

CREATE TRIGGER accounts_memberships_set_user_tracking BEFORE INSERT OR UPDATE ON public.accounts_memberships FOR EACH ROW EXECUTE FUNCTION public.trigger_set_user_tracking();

CREATE TRIGGER prevent_account_owner_membership_delete_check BEFORE DELETE ON public.accounts_memberships FOR EACH ROW EXECUTE FUNCTION public.prevent_account_owner_membership_delete();

CREATE TRIGGER prevent_memberships_update_check BEFORE UPDATE ON public.accounts_memberships FOR EACH ROW EXECUTE FUNCTION public.prevent_memberships_update();

CREATE TRIGGER invitations_set_timestamps BEFORE INSERT OR UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION public.trigger_set_timestamps();

CREATE TRIGGER only_team_accounts_check BEFORE INSERT OR UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION public.check_team_account();

CREATE TRIGGER update_notification_dismissed_status BEFORE UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION public.update_notification_dismissed_status();


